version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

    # Default is only 6.
    goarm:
      - 6
      - 7

    # Default is only v1.
    goamd64:
      - v1
      - v2
      - v3

# Disable compressing builds as ".tar.gz" file
archives:
  - formats:
    - binary

# Configure the checksums filename, to allow the attestation to pick up the correct filename
checksum:
  name_template: checksums.txt

sboms:
  - artifacts: binary
    documents:
      - "{{ .ArtifactName }}.sbom.json"
