name: Continuous Integration
on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          install-go: false

      - name: Run tests
        run: go test -race -vet=off ./...
