name: Docker image build and push
on:
  workflow_dispatch: { }

permissions:
  contents: read
  id-token: write  # needed for attestations
  attestations: write  # needed for attestations
  packages: write  # to push images

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and verify GitHub CLI
        run: |
          set -e
          curl -L -o github-cli.tar.gz https://github.com/cli/cli/releases/download/v2.65.0/gh_2.65.0_linux_amd64.tar.gz
          
          sha256digest=$(shasum -a 256 github-cli.tar.gz | cut -d ' ' -f 1)
          
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" --fail \
            https://api.github.com/orgs/cli/attestations/sha256:$sha256digest | jq '.attestations[0].bundle' > cli-attestation.json
          
          cosign verify-blob-attestation --bundle cli-attestation.json --new-bundle-format \
            --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
            --certificate-identity-regexp="^https://github.com/cli/cli/.github/workflows/deployment.yml@refs/heads/trunk$" \
            github-cli.tar.gz
          
          # The "gh" CLI is in a "gh_<version>_<os>_<cpu-arch>/bin subdirectory, so we extract it directly
          tar --wildcards --strip-components=2 -xzf github-cli.tar.gz 'gh_*/bin/gh'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/temp-test-image2
          tags: |
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push the container
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

#      - name: Generate artifact attestation
#        uses: actions/attest-build-provenance@v2
#        with:
#          subject-name: ghcr.io/${{ github.repository_owner }}/temp-test-image
#          subject-digest: ${{ steps.build-and-push.outputs.digest }}
#          push-to-registry: true

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/mshekow/temp-test-image2:latest
          format: 'spdx-json'
          output-file: 'sbom.json'

      - name: Attest
        uses: actions/attest-sbom@v2
        id: attest
        with:
          subject-name: ghcr.io/mshekow/temp-test-image2
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          sbom-path: 'sbom.json'
          push-to-registry: true

